version: '3.1'

services:
  pythonapp:
    build: ./flask/
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'